services:
  - type: web
    name: therapy-ai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /docs
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
